# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Lambda handler for Vector Search API using DynamoDB native vector search

Uses DynamoDB SearchVectors API for semantic search with inline filtering.
Embeddings are generated by Amazon Titan Embed v2.
"""
import os
import json
import boto3
import yaml
from typing import Dict, Any, List, Optional
from botocore.exceptions import ClientError

from aws_clients import s3_client, dynamodb
from system_defaults import CONFIG_PATHS, PRESIGNED_URL_EXPIRY, THUMBNAIL_FILENAMES, DEFAULT_CATEGORY_CONFIG
from common_constants import JOB_STATUS, HTTP, CORS_HEADERS
from log_utils import log_event
from asset_jobs import get_status as get_job_status
import sdma_client


# Shared embedding utility
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'shared'))
from vector_utils import generate_embedding, EMBEDDING_DIMENSIONS

# DynamoDB client (low-level for SearchVectors)
dynamodb_client = boto3.client('dynamodb')

# Configuration
VECTOR_TABLE = os.environ.get('VECTOR_TABLE_NAME', '')
VECTOR_INDEX_NAME = os.environ.get('VECTOR_INDEX_NAME', 'embedding-index')
# The Extension's own configs live in a bucket this stack owns, not in
# SDMA's asset bucket.
EXTENSION_BUCKET = os.environ.get('EXTENSION_BUCKET', '')

# Request bounds. Every result costs a DynamoDB read and two SDMA calls, and the
# query is embedded by Bedrock and billed per token, so both are capped to keep
# one request from becoming arbitrarily expensive. The API is Cognito-authorised,
# so this bounds cost rather than blocking an anonymous attacker.
MAX_LIMIT = 100
MAX_QUERY_LENGTH = 1000

# projectId is not one of the index's INLINE_FILTER attributes, so it is applied
# after SearchVectors returns. Asking for more than the caller wants keeps a
# filtered page from coming back short. MAX_TOP_K caps what that multiplier can
# request, so a limit of 100 cannot turn into an unbounded read.
OVER_FETCH_FACTOR = 5
MAX_TOP_K = 500



def cosine_distance_to_similarity(distance) -> float:
    """Convert a DynamoDB COSINE score into the similarity the API documents.

    SearchVectors returns a *distance* under the ``Score`` key -- lower means
    more alike -- but api-spec.yaml documents ``score`` as a similarity in
    0-1 where higher is better, and every caller sorts and labels it that
    way. Returning the distance unchanged inverted the ranking: the closest
    match presented as the weakest.

    Cosine distance is ``1 - cosine_similarity``, so it spans 0-2; the upper
    half means the vectors point away from each other, which for search
    purposes is simply "no match". Clamp rather than emit a negative score,
    since the documented range is 0-1.
    """
    if distance is None:
        return 0.0
    try:
        similarity = 1.0 - float(distance)
    except (TypeError, ValueError):
        return 0.0
    return max(0.0, min(1.0, similarity))


def build_search_condition(filters: Dict[str, Any]) -> Optional[str]:
    """
    Build DynamoDB SearchConditionExpression from filters.

    DynamoDB vector index inline filters support equality (=) only.
    The SearchSchema HASH key (category) is required when defined.

    Args:
        filters: Filter criteria from search request

    Returns:
        SearchConditionExpression string or None
    """
    conditions = []
    expression_values = {}
    expression_names: Dict[str, str] = {}

    # Category is the vector index partition key — required for partitioned search
    if filters.get('category'):
        conditions.append('category = :category')
        expression_values[':category'] = {'S': filters['category']}

    # Only the index's INLINE_FILTER attributes may appear here. projectId is
    # *not* one of them, so putting it in this expression made SearchVectors
    # fail with ValidationException -- a filter api-spec.yaml documents and that
    # worked in browse mode, where Scan can filter on any attribute. It is
    # applied after the search instead; see search_assets.

    if filters.get('style'):
        # 'style' is a DynamoDB reserved word, so it must be aliased even here.
        # Sending it bare made SearchVectors fail with ValidationException
        # ("Attribute name is a reserved keyword"), so the documented style
        # filter returned HTTP 500 on every ranked search while working in
        # browse, where the Scan path aliased it separately.
        conditions.append('#style = :style')
        expression_names['#style'] = 'style'
        expression_values[':style'] = {'S': filters['style']}

    # The filter keys are the plural ones api-spec.yaml documents, and only
    # those. The index stores a single scalar per asset -- `primaryMaterial`,
    # `primaryColor` -- so a multi-select in the UI can only be applied as its
    # first choice. Accepting the stored attribute names as extra aliases was
    # undocumented surface that no client sent.
    if filters.get('materials'):
        mat = filters['materials']
        if isinstance(mat, list):
            mat = mat[0] if mat else ''
        if mat:
            conditions.append('primaryMaterial = :primaryMaterial')
            expression_values[':primaryMaterial'] = {'S': mat}

    if filters.get('primaryColors'):
        color = filters['primaryColors']
        if isinstance(color, list):
            color = color[0] if color else ''
        if color:
            conditions.append('primaryColor = :primaryColor')
            expression_values[':primaryColor'] = {'S': color}

    if not conditions:
        return None, None, None

    return ' AND '.join(conditions), expression_values, expression_names or None


def search_assets(
    query: str,
    filters: Dict[str, Any] = None,
    top_k: int = 10
) -> List[Dict[str, Any]]:
    """
    Execute semantic search using DynamoDB SearchVectors.

    Generates a query embedding with Titan Embed v2, then calls
    DynamoDB SearchVectors with optional inline filters.

    Args:
        query: Search query text
        filters: Optional filter criteria
        top_k: Number of results to return

    Returns:
        List of matching assets with scores and metadata
    """
    if not VECTOR_TABLE:
        raise ValueError("VECTOR_TABLE_NAME not configured")

    filters = filters or {}
    # Only the index's four INLINE_FILTER attributes (category, style,
    # primaryMaterial, primaryColor) may appear in a SearchConditionExpression.
    # The rest of the documented filters are applied to the results instead,
    # which means asking for more than top_k because the ones that do not match
    # are discarded afterwards. Same shape as the browse path's Scan loop, where
    # Limit is applied before FilterExpression.
    #
    # Leaving them out of both places is what made projectId, subcategory and
    # sizeCategory silently ignored on ranked search while working in browse.
    post_filters = {k: filters[k] for k in ('projectId', 'subcategory', 'sizeCategory')
                    if filters.get(k)}
    fetch_k = min(top_k * OVER_FETCH_FACTOR, MAX_TOP_K) if post_filters else top_k

    # Generate query embedding
    log_event('generating_query_embedding', query=query)
    query_embedding = generate_embedding(query)

    # Build search condition
    search_condition = None
    expression_values = None
    expression_names = None
    if filters:
        search_condition, expression_values, expression_names = build_search_condition(filters)

    log_event('executing_dynamodb_vector_search',
              tableName=VECTOR_TABLE,
              indexName=VECTOR_INDEX_NAME,
              topK=fetch_k,
              postFilters=sorted(post_filters) or None,
              hasFilter=search_condition is not None)

    # Build SearchVectors request
    search_params = {
        'TableName': VECTOR_TABLE,
        'IndexName': VECTOR_INDEX_NAME,
        'SearchVector': [{'N': str(v)} for v in query_embedding],
        'TopK': fetch_k,
    }

    if search_condition:
        search_params['SearchConditionExpression'] = search_condition
    if expression_values:
        search_params['ExpressionAttributeValues'] = expression_values
    if expression_names:
        search_params['ExpressionAttributeNames'] = expression_names

    # Execute SearchVectors
    try:
        response = dynamodb_client.search_vectors(**search_params)
    except ClientError as e:
        log_event('search_vectors_error',
                  error=str(e),
                  errorCode=e.response['Error']['Code'])
        raise

    matches = response.get('SearchResults', [])
    if post_filters:
        matches = [m for m in matches
                   if all(m.get('Item', {}).get(k, {}).get('S') == v
                          for k, v in post_filters.items())]
        matches = matches[:top_k]

    # Process results
    results = enrich_items(
        [(result.get('Item', {}), cosine_distance_to_similarity(result.get('Score')))
         for result in matches]
    )

    log_event('search_completed', resultCount=len(results))
    return results


def build_result(item: Dict[str, Any], score: Optional[float]) -> Dict[str, Any]:
    """Shape one vector-table item into an API result.

    ``score`` is None in browse mode, where results are listed rather than
    ranked, and the key is omitted so a client cannot mistake a placeholder
    for a real relevance value.
    """
    asset_id = item.get('assetId', {}).get('S', '')
    # Stored at index time so search never has to resolve it: SDMA has no API
    # that maps an asset id to its project, so resolving it per result would
    # cost a ListProjects plus a GetAsset probe each time.
    project_id = item.get('projectId', {}).get('S', '')

    tags = []
    if 'tags' in item and 'L' in item['tags']:
        tags = [t.get('S', '') for t in item['tags']['L']]

    asset = None
    thumbnail_url = None
    if asset_id and project_id:
        asset = sdma_client.get_asset(asset_id, project_id)
        thumbnail_url = sdma_client.get_thumbnail_url(
            asset_id, project_id, asset=asset)
    elif asset_id:
        # Indexed before projectId was stored. Re-index to restore this asset's
        # name and thumbnail.
        log_event('vector_item_missing_project', assetId=asset_id)

    result = {
        'assetId': asset_id,
        'assetName': (asset or {}).get('assetName') or item.get('title', {}).get('S', ''),
        'title': item.get('title', {}).get('S', ''),
        'description': item.get('description', {}).get('S', ''),
        'tags': tags,
        'thumbnailUrl': thumbnail_url,
        'structuredMetadata': build_structured_metadata(
            lambda k: item.get(k, {}).get('S', '')),
    }
    if score is not None:
        result['score'] = score
    return result


def enrich_items(scored_items: List[tuple]) -> List[Dict[str, Any]]:
    """Build results for many items, resolving each one's extras in parallel.

    Every result needs one DynamoDB read and two SDMA calls to resolve its
    name and thumbnail. Run sequentially that is three round trips per result
    -- for a page of 12 the request took over five seconds. The work per item
    is independent and I/O-bound, so a thread pool collapses it to roughly the
    cost of the slowest item. Ordering is preserved because the executor's map
    yields results in submission order, and search ordering is the ranking.
    """
    if not scored_items:
        return []

    from concurrent.futures import ThreadPoolExecutor

    # Capped because each worker holds a socket, and Lambda gives this
    # function modest memory; beyond this the added contention costs more
    # than the extra concurrency returns.
    workers = min(len(scored_items), 16)
    with ThreadPoolExecutor(max_workers=workers) as pool:
        return list(pool.map(lambda pair: build_result(*pair), scored_items))


def browse_assets(filters: Dict[str, Any], limit: int) -> List[Dict[str, Any]]:
    """List assets without ranking them, honouring the same metadata filters.

    Every path through search_assets embeds the query text, so there was no
    way to list or filter without one. Callers worked around that by sending
    '*', which was embedded literally and produced results ordered by their
    distance to that character -- an arbitrary order presented as relevance.

    This scans the vector table instead and returns no score, because without
    a query there is nothing to be relevant to. Scan suits the demo's scale;
    a larger catalogue would want the category partition key queried directly.
    """
    scan_params: Dict[str, Any] = {
        'TableName': VECTOR_TABLE,
    }

    # Reuse the search filter builder so browse and search agree on which
    # metadata values match. Scan's FilterExpression is not limited to the
    # index's inline filter attributes, so the attributes that ranked search has
    # to post-filter can be expressed directly here.
    condition, values, names = build_search_condition(filters)
    names = dict(names or {})

    for key in ('projectId', 'subcategory', 'sizeCategory'):
        if not filters.get(key):
            continue
        clause = f'{key} = :{key}'
        condition = f'{condition} AND {clause}' if condition else clause
        values = dict(values or {})
        values[f':{key}'] = {'S': filters[key]}

    if condition:
        scan_params['FilterExpression'] = condition
        if values:
            scan_params['ExpressionAttributeValues'] = values
        if names:
            scan_params['ExpressionAttributeNames'] = names

    log_event('executing_browse', hasFilter=condition is not None, limit=limit)

    # Scan applies Limit *before* FilterExpression, so a small Limit with a
    # filter can return an empty page while matches remain further in. Page
    # until enough matches accumulate or the table is exhausted, and cap the
    # pages so a highly selective filter cannot scan without bound.
    items: List[Dict[str, Any]] = []
    start_key = None
    for _ in range(10):
        params = dict(scan_params)
        if start_key:
            params['ExclusiveStartKey'] = start_key
        try:
            response = dynamodb_client.scan(**params)
        except ClientError as e:
            log_event('browse_error', error=str(e),
                      errorCode=e.response['Error']['Code'])
            raise
        items.extend(response.get('Items', []))
        start_key = response.get('LastEvaluatedKey')
        if len(items) >= limit or not start_key:
            break

    # Trim what the loop accumulated. Reading `response` here instead would
    # discard every earlier page and keep only the last one -- which defeats
    # the paging above, because `Limit` is applied before `FilterExpression` and
    # a filtered page can legitimately be empty while matches remain further in.
    items = items[:limit]
    results = enrich_items([(item, None) for item in items])

    # Scan returns items in no meaningful order, so give the caller a stable
    # one. The UI's own sort control then operates on a predictable baseline.
    results.sort(key=lambda r: (r.get('assetName') or '').lower())

    log_event('browse_completed', resultCount=len(results))
    return results


def get_asset_ai_metadata(asset_id: str) -> Dict[str, Any]:
    """Get AI-generated metadata for a specific asset.

    Read from this stack's vector table. This used to read aiGeneratedTags,
    aiStructuredMetadata and friends off SDMA's asset record -- attributes
    nothing ever wrote, so the endpoint always raised "Asset not found". The
    same metadata is on the vector item, which is where AI tagging stores it.
    """
    if not VECTOR_TABLE:
        raise ValueError("VECTOR_TABLE_NAME not configured")

    response = dynamodb.Table(VECTOR_TABLE).get_item(Key={'assetId': asset_id})
    item = response.get('Item')
    if not item:
        raise ValueError(f"Asset not found: {asset_id}")

    return {
        'assetId': asset_id,
        'tags': item.get('tags', []),
        'structuredMetadata': build_structured_metadata(
            lambda k: item.get(k, '')),
        'description': item.get('description', ''),
        # Presence of the item is what "indexed" means here.
        'vectorIndexed': True,
        'vectorIndexedAt': item.get('indexedAt'),
    }


def build_structured_metadata(get: Any) -> Dict[str, Any]:
    """Assemble the metadata block both read endpoints return.

    Shared so search and extended-metadata cannot drift: they used to disagree,
    search returning `materials` and `primaryColors` as lists while
    extended-metadata returned scalar `primaryMaterial`, `primaryColor` and
    `secondaryColor` -- with `api-spec.yaml` describing both through one schema.

    `get` takes an attribute name and returns its string value, which lets a
    caller holding typed client items and one holding resource-unwrapped items
    share this.

    The index stores one material and up to two colours per asset. They are
    returned as lists because that is the shape the model produces and the shape
    the UI's multi-select expects.
    """
    materials = [v for v in (get('primaryMaterial'),) if v]
    colors = [v for v in (get('primaryColor'), get('secondaryColor')) if v]
    return {
        'category': get('category'),
        'subcategory': get('subcategory'),
        'style': get('style'),
        'materials': materials,
        'primaryColors': colors,
        'sizeCategory': get('sizeCategory'),
    }


def get_category_config() -> Dict[str, Any]:
    """Return the filter vocabularies the UI offers in its dropdowns.

    These must be the same values the AI tagger was told to choose from, or the
    UI offers filters that match nothing. They live in the tagging config's
    ``filter_attributes`` -- the one place that vocabulary is defined -- and
    deploy.sh uploads that file. This previously read a separate
    ``config/categories/default.json`` that nothing writes, so every request
    hit NoSuchKey and returned the all-empty fallback, leaving each dropdown
    with only its "All" entry.
    """
    key = CONFIG_PATHS['tagging']
    try:
        response = s3_client.get_object(Bucket=EXTENSION_BUCKET, Key=key)
        config = yaml.safe_load(response['Body'].read().decode('utf-8')) or {}
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            log_event('category_config_missing', bucket=EXTENSION_BUCKET, key=key)
            return DEFAULT_CATEGORY_CONFIG.copy()
        raise
    except yaml.YAMLError as e:
        log_event('category_config_unparseable', key=key, error=str(e))
        return DEFAULT_CATEGORY_CONFIG.copy()

    attrs = config.get('filter_attributes') or {}

    # The tagging config nests each category's subcategories under a
    # description; the UI wants a plain category -> [subcategory] mapping.
    categories = {
        name: (spec or {}).get('subcategories', [])
        for name, spec in (attrs.get('categories') or {}).items()
    }

    return {
        'categories': categories,
        'styles': attrs.get('styles') or [],
        'materials': attrs.get('materials') or [],
        'colors': attrs.get('colors') or [],
    }


def get_assets_status(asset_ids: List[str]) -> List[Dict[str, Any]]:
    """Get processing status for multiple assets.

    Read from this stack's own jobs table. These fields used to live on SDMA's
    asset record, which meant the Extension wrote its own attributes into a
    table it does not own.
    """
    statuses = []

    for asset_id in asset_ids:
        item = get_job_status(asset_id)
        statuses.append({
            'assetId': asset_id,
            # No row means the asset has not been picked up yet, which a caller
            # cannot distinguish from pending.
            'renderJobStatus': item.get('renderJobStatus', JOB_STATUS['pending']),
            'aiTagJobStatus': item.get('aiTagJobStatus', JOB_STATUS['pending']),
            'renderJobUpdatedAt': item.get('renderJobUpdatedAt'),
            'aiTagJobUpdatedAt': item.get('aiTagJobUpdatedAt'),
        })

    return statuses


def create_response(status_code: int, body: Any) -> Dict[str, Any]:
    """Create API Gateway response with CORS headers"""
    return {
        'statusCode': status_code,
        'headers': {
            'Content-Type': HTTP['content_type_json'],
            **CORS_HEADERS
        },
        'body': json.dumps(body)
    }


def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Lambda handler for Vector Search API

    Endpoints:
    - POST /assets/search: Semantic search with metadata filtering (RESTful)
    - GET /assets/status: Get processing status for assets
    - GET /assets/{assetId}/extended-metadata: Get extended metadata for asset
    - GET /categories: Get category configuration for filters

    Request body for /assets/search:
    {
        "query": "search query",
        "filters": {
            "category": "furniture",
            "style": "modern",
            "materials": "wood"
        },
        "limit": 10
    }
    """
    log_event('lambda_invoked',
              httpMethod=event.get('httpMethod'),
              path=event.get('path'))

    http_method = event.get('httpMethod', '')
    path = event.get('path', '')

    try:
        # POST /assets/search
        if http_method == 'POST' and path.rstrip('/').endswith('/assets/search'):
            body = json.loads(event.get('body', '{}'))

            query = (body.get('query') or '').strip()
            limit = body.get('limit', 10)
            filters = body.get('filters', {})

            # Bound both inputs. Each result costs a DynamoDB read plus two SDMA
            # calls, and the query is embedded by Bedrock and billed per token,
            # so an unbounded value lets an authenticated caller turn one request
            # into an arbitrarily expensive one.
            try:
                limit = int(limit)
            except (TypeError, ValueError):
                return create_response(400, {'error': 'limit must be an integer'})
            if not 1 <= limit <= MAX_LIMIT:
                return create_response(
                    400, {'error': f'limit must be between 1 and {MAX_LIMIT}'})
            if len(query) > MAX_QUERY_LENGTH:
                return create_response(
                    400, {'error': f'query must be at most {MAX_QUERY_LENGTH} characters'})

            # No query means browse: list assets, optionally filtered, with no
            # score. Ranking requires something to be relevant to, so results
            # carry no score field rather than a placeholder.
            if not query:
                results = browse_assets(filters, limit)
                return create_response(200, {
                    'success': True,
                    'query': None,
                    'filters': filters,
                    'mode': 'browse',
                    'resultCount': len(results),
                    'results': results
                })

            results = search_assets(query, filters, limit)
            return create_response(200, {
                'success': True,
                'query': query,
                'filters': filters,
                'mode': 'semantic',
                'resultCount': len(results),
                'results': results
            })

        # GET /assets/status
        elif http_method == 'GET' and path.rstrip('/').endswith('/assets/status'):
            query_params = event.get('queryStringParameters', {}) or {}
            ids_param = query_params.get('ids', '')
            if not ids_param:
                return create_response(400, {'error': 'Missing required parameter: ids'})
            asset_ids = [aid.strip() for aid in ids_param.split(',') if aid.strip()]
            if not asset_ids:
                return create_response(400, {'error': 'No valid asset IDs provided'})
            if len(asset_ids) > 100:
                return create_response(400, {'error': 'Maximum 100 asset IDs allowed'})
            statuses = get_assets_status(asset_ids)
            return create_response(200, {'success': True, 'statuses': statuses})

        # GET /assets/{assetId}/extended-metadata
        elif http_method == 'GET' and '/assets/' in path and '/extended-metadata' in path:
            asset_id = event.get('pathParameters', {}).get('assetId')
            if not asset_id:
                return create_response(400, {'error': 'Missing asset ID'})
            metadata = get_asset_ai_metadata(asset_id)
            return create_response(200, {'success': True, **metadata})

        # GET /categories
        elif http_method == 'GET' and path.rstrip('/').endswith('/categories'):
            config = get_category_config()
            return create_response(200, {'success': True, **config})

        # OPTIONS (CORS preflight)
        elif http_method == 'OPTIONS':
            return create_response(200, {})

        else:
            return create_response(404, {
                'error': 'Endpoint not found',
                'path': path,
                'method': http_method
            })

    except ValueError as e:
        log_event('validation_error', error=str(e))
        return create_response(400, {'error': str(e)})

    except ClientError as e:
        error_code = e.response['Error']['Code'] if hasattr(e, 'response') else 'Unknown'
        log_event('aws_client_error', error=str(e), errorCode=error_code)
        return create_response(500, {'error': f"AWS service error: {error_code}"})

    except Exception as e:
        log_event('unexpected_error', error=str(e), errorType=type(e).__name__)
        return create_response(500, {'error': 'Internal server error'})
